version: '3'

services:
  web:
    image: nginx
    ports:
      - "${WEB_PORT:-8080}:80"
    container_name: my-web-container

  database:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: my-database-container
