version: '3'

networks:
  my_custom_network:
    driver: bridge

services:
  web:
    image: nginx
    ports:
      - "${WEB_PORT:-8080}:80"
    container_name: my-web-container
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - my_custom_network

  database:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: my-database-container
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_custom_network

volumes:
  pg_data:

